### PR TITLE
Fixes modal close button positioning issue

### PR DESCRIPTION
**Pull request by tboyko**
When a modal has a lengthy title, or the modal div is narrow, the `h3` title can fill the entire horizontal width of the modal. When this happens, the `x` close button is bumped down the screen incorrectly. 

This fork moves the close link html above the `h3` tag, as is specified by the twitter bootstrap documentation. It also removes additional css that was added at some point which causes the `h3` title to bump down the screen as well.

### CODE REVIEW

**Comment by tboyko** [comment]
Note: this issue only seems to happen in Internet Explorer.

**Comment by nikku** [comment]
Looks like your pull request breaks the load indicator. 
Any thoughts?

**Comment by nikku** [comment]
Resolved it in `master` and `2.0-wip` by exchanging the `loader` and `h3` elements.
Can you check if the issue still exists in IE?

**Comment by tboyko** [comment]
Yes, that fixes it. Thanks for the assist!

**Pull request closed without merging**
